name: Daily Scheduled Workflow

on:
  schedule:
    # Run every day at 2:30 PM UTC
    - cron: '25 07 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a scheduled task
        run: echo "This job runs daily at 07:11 AM UTC"
