name: Daily Scheduled Workflow

on:
  schedule:
    # Run every day at 2:30 PM UTC
    - cron: '10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a scheduled task
        run: Timestamp=$(date +"%Y-%m-%d_%H:%M:%S"); echo "This job runs every hour at ${Timestamp}" 
